{{- if .Values.stackrox.enabled }}
apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: stackrox-secured-cluster-services
  namespace: {{ .Values.stackrox.namespace | quote }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "25"
spec:
  admissionControl:
    listenOnCreates: false
    listenOnEvents: true
    listenOnUpdates: false
  auditLogs:
    collection: Auto
  centralEndpoint: 'central.stackrox:443'
  clusterName: {{ .Values.stackrox.clusterName | quote }}
  perNode:
    collector:
      collection: KernelModule
      imageFlavor: Regular
    taintToleration: TolerateTaints
{{- end }}