{{- if and .Values.gitlab (not .Values.subscriptions.only) }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: "{{ $.Values.gitlab_app_name }}-user"
  namespace: "{{ .Values.gitlab.namespace }}"
{{- end -}}
